tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ./cmd/main.go"  # <- point to cmd/main.go
  bin = "tmp/main"
  full_bin = "./tmp/main"
  include_ext = ["go"]
  exclude_dir = ["vendor", "tmp"]

[log]
  time = true
